### ISSUE TITLE
npm run generate doesn't work with example-auth0?

### ISSUE THREAD

**Issue by kodekrendel** [nuxt/example-auth0#7]
I got an error:

```
TypeError: Cannot read property 'headers' of undefined
    at getUserFromCookie (server-bundle.js:1544:11)
    at module.exports.__webpack_exports__.default (server-bundle.js:2084:124)
    at promisify (server-bundle.js:1214:15)
    at promiseSeries (server-bundle.js:1195:10)
    at server-bundle.js:1840:96
```

**Comment by Atinux** [comment]
Hi @kodekrendel  

It should work now, indeed, `req` does not exists when we run `nuxt generate`.

See my commit: https://github.com/nuxt/example-auth0/commit/d14b88f01d3c6d5b49c7d65435f93cd75ae1c3a9
